py_library(
    name = "detector",
    srcs = ["detector.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "detector_test",
    srcs = ["detector_test.py"],
    deps = [":detector"],
)
